# ArgoCD Application: GitOps sync course-service từ git (dùng values-local.yaml).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: course-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/leloc70/eduvn-elearning-eks.git
    targetRevision: main
    path: charts/course-service
    helm:
      valueFiles:
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: eduvn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
